# Matrix indices warmup

In [2]:
import numpy as np

Write nested loops to create each of the following 5x5 matrices, starting from a zero matrix. Use 'c' and 'r' as the names of your index variables (this really helps your brain.) Use a counter, too!

$$
\begin{bmatrix}
  1 &  0 &  0 &  0 &  0\\
  2 &  6 &  0 &  0 &  0\\
  3 &  7 &  10 &  0 &  0\\
  4 &  8 &  11 &  13 &  0\\
  5 &  9 &  12 &  14 &  15
\end{bmatrix}
$$

$$
\begin{bmatrix}
  0 &  0 &  0 &  0 &  0\\
  1 &  0 &  0 &  0 &  0\\
  2 &  5 &  0 &  0 &  0\\
  3 &  6 &  8 &  0 &  0\\
  4 &  7 &  9 &  10 &  0
\end{bmatrix}
$$

$$
\begin{bmatrix}
  15 &  14 &  12 &  9 &  5\\
  0 &  13 &  11 &  8 &  4\\
  0 &  0 &  10 &  7 &  3\\
  0 &  0 &  0 &  6 &  2\\
  0 &  0 &  0 &  0 &  1
\end{bmatrix}
$$

$$
\begin{bmatrix}
  0 &  10 &  9 &  7 &  4\\
  0 &  0 &  8 &  6 &  3\\
  0 &  0 &  0 &  5 &  2\\
  0 &  0 &  0 &  0 &  1\\
  0 &  0 &  0 &  0 &  0
\end{bmatrix}
$$

In [3]:
A = np.zeros((5,5), np.int32)

In [9]:
# Solution 1 Here
B = np.array(A)
counter = 1
for c in range(5):
    for r in range(c, 5):
        B[r][c] = counter
        counter += 1
B

array([[ 1,  0,  0,  0,  0],
       [ 2,  6,  0,  0,  0],
       [ 3,  7, 10,  0,  0],
       [ 4,  8, 11, 13,  0],
       [ 5,  9, 12, 14, 15]], dtype=int32)

In [13]:
# Solution 2 Here
C = np.array(A)
counter = 1
for c in range(5):
    for r in range(4, c, -1):
        C[r][c] = counter
        counter += 1
C

array([[ 0,  0,  0,  0,  0],
       [ 4,  0,  0,  0,  0],
       [ 3,  7,  0,  0,  0],
       [ 2,  6,  9,  0,  0],
       [ 1,  5,  8, 10,  0]], dtype=int32)

In [29]:
# Solution 3 Here
D = np.array(A)
counter = 1
for c in range(4, -1, -1):
    for r in range(c, -1, -1):
        D[r][c] = counter
        counter += 1
D

array([[15, 14, 12,  9,  5],
       [ 0, 13, 11,  8,  4],
       [ 0,  0, 10,  7,  3],
       [ 0,  0,  0,  6,  2],
       [ 0,  0,  0,  0,  1]], dtype=int32)

In [30]:
# Solution 4 Here
E = np.array(A)
counter = 1
for c in range(4, -1, -1):
    for r in range(c - 1, -1, -1):
        E[r][c] = counter
        counter += 1
E

array([[ 0, 10,  9,  7,  4],
       [ 0,  0,  8,  6,  3],
       [ 0,  0,  0,  5,  2],
       [ 0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0]], dtype=int32)