# 2D Motion with Drag
Arush Bodla  
Block 2 AP Physics C

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp

My situation is Pranav kicking a soccer ball across the field to score a goal.   
Here are the different initial values:

In [2]:
# Projectile info: Drag Coefficient (Cd), Radius (r), Mass (m), Cross Sectional Area (A)
Cd = 0.5
r = 0.11
A = np.pi * r**2
m = 0.5

# Environment info: Air Density (rho_air), Gravity (g)
rho_air = 1.28
g = 9.81



$F_d = \frac{1}{2}\rho_a C_d A v^2 = bv^2$  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$\frac{1}{2}\rho_a C_d A v^2 = bv^2$  
  
&nbsp;&nbsp;&nbsp;$b = \frac{1}{2} \rho_a C_d A$


In [3]:
b = 0.5 * Cd * A * rho_air

v0 = 25
theta = np.pi / 4

In [4]:
def deriv(t, u):
    x, vx, y, vy = u
    speed = np.sqrt(vx**2 + vy**2)
    ax = -b/m * speed * vx
    ay = -b/m * speed * vy - g
    return vx, ax, vy, ay

In [5]:
# Initial Conditions
u0 = 0, v0 * np.cos(theta), 0, v0 * np.sin(theta)

#Time span
t0 = 0
tf = 10

In [6]:
def hit_target(t, u):
    return u[2]

hit_target.terminal = True
hit_target.direction = -1

In [7]:
def max_height(t, u):
    return u[3]

In [8]:
solution = solve_ivp(deriv, [t0, tf], u0, dense_output=True, events=[hit_target, max_height])

In [9]:
t = ((2 * v0) * np.sin(theta)) / g
t1 = np.linspace(0, t, 1000)

xnd = v0 * np.cos(theta) * t1
ynd = v0 * np.sin(theta) * t1 - 0.5 * g * t1**2

In [10]:
print(solution)

  message: A termination event occurred.
  success: True
   status: 1
        t: [ 0.000e+00  5.657e-05  6.222e-04  6.279e-03  6.284e-02
             5.604e-01  1.396e+00  2.762e+00  2.885e+00]
        y: [[ 0.000e+00  9.999e-04 ...  3.040e+01  3.126e+01]
            [ 1.768e+01  1.768e+01 ...  7.154e+00  6.867e+00]
            [ 0.000e+00  9.999e-04 ...  1.449e+00 -1.998e-15]
            [ 1.768e+01  1.768e+01 ... -1.150e+01 -1.221e+01]]
      sol: <scipy.integrate._ivp.common.OdeSolution object at 0x7f63d226c310>
 t_events: [array([ 2.885e+00]), array([ 1.330e+00])]
 y_events: [array([[ 3.126e+01,  6.867e+00, -1.998e-15, -1.221e+01]]), array([[ 1.773e+01,  1.061e+01,  1.032e+01,  1.776e-15]])]
     nfev: 56
     njev: 0
      nlu: 0


In [14]:
print(f'Time to target: {t:.2f} s')
print(f'Time to max height: {solution.t_events[1][0]:.2f} s')

Time to target: 3.60 s
Time to max height: 1.33 s


In [ ]:
T = np.linspace(0, solution.t_evevents[0][0], 1000)
